GyakolroWebApp/GyakolroWebApp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyakolroWebApp.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Contact/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Contact/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Contact/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Contact/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Contact/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Contact/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Contact/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GyakolroWebApp/GyakolroWebApp/Controllers/ListaModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GyakolroWebApp.Controllers
{
    public class ListaModelController : Controller
    {
        
        //
        // GET: /ListaModel/

        public ActionResult Index()
        {       
            
            GyakolroWebApp.Models.ListaModel lm = new Models.ListaModel();
            try
            {
                foreach (var fr in lm.FoRootCsp())
                {               
                lm.froot.Add(fr);
                foreach (var rcs in lm.rootCsp(fr.mhID))
                {
                    lm.root.Add(rcs);
                    foreach (var gycs in lm.gyerekCsp(rcs.mhID))
                    {
                        lm.gy.Add(gycs);
                        foreach (var gyr in lm.gyerekCsp(gycs.mhID))
                        {
                            lm.gyRoot.Add(gyr);
                        }
                    }
                }
                }
                ViewBag.dlista = lm.dolgozoLista();
            }
            catch (Exception ex)
            {
                ViewBag.Hiba = "Hiba a feldolgozásában! " + ex.Message;
            }
            
            ViewBag.lista = lm.root;
            ViewBag.allista = lm.gy;
            ViewBag.GyAllista = lm.gyRoot;
            return View();
        }
    }
}

GyakolroWebApp/GyakolroWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="hu">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Fő oldal</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body background= "../../Images/hatterkep_1366x768_0200.jpg">
        <header>
            <div class="content-wrapper">
                <p style="font-family: Arial, Helvetica, sans-serif; font-size: xx-large; 
                    font-style: normal; font-weight: bold; color: #99FF66"><b>Cég adatbázis</b></p>                
            </div>
            <div>
            <nav>
                  <ul id="menu">
                  <li>@Html.ActionLink("Adatok", "Index", "ListaModel")</li>
                  <li>|</li>                   
                  <li>@Html.ActionLink("Kapcsolat", "Index", "Contact")</li>                                                           
                  </ul>
            </nav>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="footer_box">
                <div>
                    <h3>Készítette: Sápi Sándor - 2015</h3>                                   
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>